dict_config = {
    "attendants": [
        {"id": "porta1", "pos": {"x": 2, "y": 1}, "processing_time": [5, 15]},
        {"id": "porta2", "pos": {"x": 4, "y": 1}, "processing_time": [3, 20]},
        {"id": "CNH1", "pos": {"x": 8, "y": 11}, "processing_time": 30},
        {"id": "RG1", "pos": {"x": 10, "y": 11}, "processing_time": 30},
        {"id": "TITULO1", "pos": {"x": 12, "y": 11}, "processing_time": 30},
    ],
    "queues": [
        {
            "order": 0,
            "accepts": ["CNH", "RG", "TITULO", "AGENDAMENTO"],
            "attendants": ["porta1", "porta2"],
            "wait_spots": [
                {"x": 1, "y": 5},
                {"x": 1, "y": 6},
                {"x": 2, "y": 6},
                {"x": 3, "y": 6},
                {"x": 4, "y": 6},
                {"x": 4, "y": 7},
                {"x": 4, "y": 8},
                {"x": 3, "y": 8},
                {"x": 2, "y": 8},
                {"x": 1, "y": 8},
                {"x": 1, "y": 9},
            ],
        },
        {
            "order": 1,
            "accepts": ["CNH"],
            "attendants": ["CNH1"],
            "wait_spots": [
                {"x": 8, "y": 9},
                {"x": 8, "y": 8},
                {"x": 8, "y": 7},
                {"x": 8, "y": 6},
                {"x": 8, "y": 5},
            ],
        },
        {
            "order": 1,
            "accepts": ["RG"],
            "attendants": ["RG1"],
            "wait_spots": [
                {"x": 10, "y": 9},
                {"x": 10, "y": 8},
                {"x": 10, "y": 7},
                {"x": 10, "y": 6},
                {"x": 10, "y": 5},
            ],
        },
           {
            "order": 1,
            "accepts": ["TITULO"],
            "attendants": ["TITULO1"],
            "wait_spots": [
                {"x": 12, "y": 9},
                {"x": 12, "y": 8},
                {"x": 12, "y": 7},
                {"x": 12, "y": 6},
                {"x": 12, "y": 5},
            ],
        },
    ],
    "entrances": [
        {"pos": {"x": 0, "y": 11}, "rate": 5, "accepts": ["CNH", "RG", "TITULO", "AGENDAMENTO"]},
    ],
    "exits": [
        {"pos": {"x": 6, "y": 12}, "accepts": ["CNH", "RG", "TITULO", "AGENDAMENTO"]},
    ],
    "groups": [
        {"name": "CNH", "amount": 7},
        {"name": "RG", "amount": 5},
        {"name": "TITULO", "amount": 6},
    ],
    "worldmap": [
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ],
        [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, ],
        [1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, ],
        [1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, ],
        [1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, ],
        [1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, ],
        [1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, ],
        [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, ],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, ],
        [1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, ],
    ]
}
